import AltRegularity.GMT.Varifold

/-!
# AltRegularity.GMT.SecondVariation

Second variation of a varifold along a normal deformation.

For a smooth varifold supported on a hypersurface $\Sigma$ with second
fundamental form $A$, the second variation along a scalar normal
deformation $\varphi$ has the classical form
$\delta^2 V(\varphi, \varphi) = \int_\Sigma \bigl(|\nabla \varphi|^2 -
|A|^2 \varphi^2\bigr)\, d\mathcal{H}^n.$

This is the GMT primitive used to express:
  * Stability — paper §4 Definition 4.1 (S2)
    (`AltRegularity.Regularity.AlphaStructural`)
  * Local stability of varifolds — paper §7.1
    (`AltRegularity.Regularity.StabilityVerification`)

Encoded as an opaque leaf primitive pending Mathlib's smooth-manifold
infrastructure for vector fields and second variation.
-/

namespace AltRegularity

variable {M : Type*} [MetricSpace M] [MeasurableSpace M] [BorelSpace M]

namespace Varifold

/-- The **second variation** of $V$ along a smooth scalar normal
deformation $\varphi$, $\delta^2 V(\varphi, \varphi) \in \mathbb{R}$.

This is the second derivative of the total mass under the one-parameter
family of varifolds generated by infinitesimal normal deformation
$\varphi$. For a smooth varifold supported on a hypersurface $\Sigma$
with second fundamental form $A$, it equals
$\int_\Sigma (|\nabla \varphi|^2 - |A|^2 \varphi^2)\, d\mathcal{H}^n$. -/
opaque secondVariation : Varifold M → (M → ℝ) → ℝ

end Varifold

end AltRegularity
