import GeometricMeasureTheory.Varifold

/-!
# AltRegularity.GMT.SecondVariation

Second variation of a varifold along a normal deformation.

For a smooth varifold supported on a hypersurface $\Sigma$ with second
fundamental form $A$, the second variation along a scalar normal
deformation $\varphi$ has the classical form
$\delta^2 V(\varphi, \varphi) = \int_\Sigma \bigl(|\nabla \varphi|^2 -
|A|^2 \varphi^2\bigr)\, d\mathcal{H}^n.$

This is the GMT primitive used to express:
  * Stability — paper §4 Definition 4.1 (S2)
    (`AltRegularity.Regularity.AlphaStructural`)
  * Local stability of varifolds — paper §7.1
    (`AltRegularity.Regularity.StabilityVerification`)

Encoded as an opaque leaf primitive pending Mathlib's smooth-manifold
infrastructure for vector fields and second variation.
-/

namespace GeometricMeasureTheory

variable {M : Type*} [MetricSpace M] [MeasurableSpace M] [BorelSpace M] [MeasureTheory.MeasureSpace M]

namespace Varifold

/-- The **second variation** of $V$ along a smooth scalar normal
deformation $\varphi$, $\delta^2 V(\varphi, \varphi) \in \mathbb{R}$.

This is the second derivative of the total mass under the one-parameter
family of varifolds generated by infinitesimal normal deformation
$\varphi$. For a smooth varifold supported on a hypersurface $\Sigma$
with second fundamental form $A$, it equals (in a Riemannian ambient):
$$\delta^2 V(\varphi, \varphi)
  = \int_\Sigma \bigl(|\nabla \varphi|^2 - (|A|^2 + \mathrm{Ric}(\nu, \nu))
                  \varphi^2\bigr)\, d\|V\|.$$

**Ground truth**: Simon 1983 §49 (Jacobi field setup, second variation
formula for stationary integral varifolds); Schoen–Simon 1981 §1
(stable hypersurfaces).

**Why opaque** (Layer B C-3 retreat):

A paper-faithful def would require three pieces of Riemannian
infrastructure not currently in Mathlib:

  * **Manifold gradient $\nabla \varphi$**: Mathlib has `mfderiv` (the
    manifold differential) but no canonical gradient operator
    (which requires a metric to identify $T^*M$ with $TM$). Mathlib's
    `Geometry/Manifold/Riemannian/` has the metric tensor but does not
    expose `gradient` or `‖∇φ‖²` as a top-level def.
  * **Second fundamental form $A$**: requires the normal bundle of the
    rectifiable support of $V$ inside $M$, plus the Riemannian
    connection $\nabla$. Neither is available; building the immersed
    second fundamental form would need ~300 LOC of supporting
    infrastructure.
  * **Ricci curvature $\mathrm{Ric}$**: Mathlib has Riemannian metric +
    (in progress) Levi–Civita connection, but no `Ricci` operator
    yet exposed at this level.

Once Mathlib upgrades `Riemannian/` with `gradient`, second fundamental
form for immersed hypersurfaces, and Ricci, this opaque can be replaced
by the explicit Jacobi formula above.

**Used by**: `Varifold.IsStable` (`Regularity/AlphaStructural.lean`),
`Varifold.LocallyStable` (`Regularity/StabilityVerification.lean`). -/
opaque secondVariation : Varifold M → (M → ℝ) → ℝ

end Varifold

end GeometricMeasureTheory
